### ISSUE TITLE
toolbox deploy fail

### ISSUE THREAD

**Issue by gido** [frontend/toolbox-utils#21]
The `deploy` task depends on [gulp-gh-pages](https://github.com/shinnn/gulp-gh-pages) plugin which it's self depend on module `gift`.

The required version of `gift` in `gulp-gh-pages` have a bug and neeed to be upgraded to the latest version.

Follow:
 - shinnn/gulp-gh-pages#116
 - notatestuser/gift#96
 - and PR shinnn/gulp-gh-pages#117

**Comment by Yago** [comment]
Until this PR is merged, we can do `$ cd node_modules/gulp-gh-pages/ && npm install gift@0.10.1`

**Comment by gido** [comment]
ping !
Looks like PR are merged after 2 years :)

**Comment by dmrty** [comment]
Woohoo 😱👏👏👏👏
